### ISSUE TITLE
Crash when receiving reward

### ISSUE THREAD

**Issue by alxnns1** [navneetset/pebbles-crate#4]
Version: 1.0.3-1.20.1

The server that I am an admin experienced a crash when a player received a reward from a crate.
The crates have been used for a while now and this is the first time it has crashed.
The player received the reward even though the server crashed.

The config with the reward in question
![image](https://github.com/navneetset/pebbles-crate/assets/485571/ec185330-a8dd-4389-9993-7f22aa1ff3d3)

The log output of the moment of the crash
![image](https://github.com/navneetset/pebbles-crate/assets/485571/991d4278-e3f6-4939-bf13-7c3b81c4167d)

**Comment by navneetset** [comment]
Looks like there's an extra comma after your last command, can you see if removing that resolves the issue?

**Comment by alxnns1** [comment]
You're absolutely right, that fixed the crash. Thank you!
